[package]
name = "shisui"
version = "0.1.0"
license = "GPL-3.0-or-later"
keywords = ["starknet", "defi", "syntethics"]


# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.4.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.16.0" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0" }
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib"}
alexandria_storage = { git = "https://github.com/keep-starknet-strange/alexandria.git", tag="cairo-v2.3.0-rc0"}

[[target.starknet-contract]]
sierra = true
casm = true

[cairo]
sierra-replace-ids = true

[tool.snforge]
exit_first = false
