name: Install dependencies

runs:
  using: composite

  steps:    
      - name: Step 1 - Install Scarb
        uses: software-mansion/setup-scarb@v1.3.2
        with:
          scarb-version: 2.3.1
      - name: Step 2 - Install snforge
        uses: foundry-rs/setup-snfoundry@v2
        with:
          starknet-foundry-version: 0.11.0
      - name: Step 3 - Restore compilation cache
        uses: actions/cache/restore@v3
        with:
          path: |
            target
          key: build-${{ github.ref_name }}
          restore-keys: |
            build-${{ github.base_ref }}
            build-

      